
--ORACLE SQL
--id NUMBER GENERATED by default on null as IDENTITY

--DDL
CREATE TABLE pessoa (
  id NUMBER(2) CONSTRAINT Pk_pessoa PRIMARY KEY
  ,cpf VARCHAR(11) NOT NULL
  ,nome VARCHAR(250) NOT NULL
);

CREATE TABLE produto (
  id NUMBER(2) CONSTRAINT Pk_produto PRIMARY KEY
  ,descricao VARCHAR(50) NOT NULL
  ,valor_unitario NUMERIC(10,2) NOT NULL
);

CREATE TABLE pedido (
  id NUMBER(2) CONSTRAINT Pk_pedido PRIMARY KEY
  ,pessoa NUMBER(2) CONSTRAINT Fk_pessoa REFERENCES pessoa
--  ,item NUMBER(2) CONSTRAINT Fk_item REFERENCES item
);

CREATE TABLE pedidoItem (
	id NUMBER(2) CONSTRAINT Pk_pedidoItem PRIMARY KEY
	,quantidade NUMBER(2) NOT NULL
	,produto NUMBER(2) CONSTRAINT Fk_produto REFERENCES produto
	,pedido NUMBER(2) CONSTRAINT Fk_pedido REFERENCES pedido
);

--DML
INSERT INTO pessoa (id, cpf, nome) VALUES (1,'56637927082', 'Pessoa 1');
INSERT INTO pessoa (id, cpf, nome) VALUES (2,'56637927082', 'Pessoa 2');


INSERT INTO produto (id, descricao, valor_unitario) VALUES (1, 'Produto 1', 10.0);
INSERT INTO produto (id, descricao, valor_unitario) VALUES (2, 'Produto 2', 20.0);
INSERT INTO produto (id, descricao, valor_unitario) VALUES (3, 'Produto 3', 20.0);

INSERT INTO pedido (id, pessoa) VALUES (1, 1);
INSERT INTO pedido (id, pessoa) VALUES (2, 2);

INSERT INTO pedidoItem (id, quantidade, pedido, produto) VALUES (1, 2, 1, 1);
INSERT INTO pedidoItem (id, quantidade, pedido, produto) VALUES (2, 1, 2, 1);

DROP TABLE PRODUTO
DROP TABLE PESSOA
DROP TABLE PEDIDO
DROP TABLE PEDIDOITEM

--DQL
SELECT * FROM PESSOA pes
SELECT * FROM PRODUTO pro
SELECT * FROM PEDIDO ped
SELECT * FROM PEDIDOITEM

