set serveroutput on

CREATE OR REPLACE FUNCTION FUN_CALCULA_FGTS(P_VAL NUMBER) RETURN NUMBER IS

BEGIN
  RETURN P_VAL * 0.08;
END FUN_CALCULA_FGTS;

/
CREATE OR REPLACE PROCEDURE PROC1 IS
V_VALOR NUMBER;
BEGIN
V_VALOR := FUN_CALCULA_FGTS(5000); DBMS_OUTPUT.PUT_LINE('O VALOR DO FGTS É: ' || TO_CHAR(V_Valor));
END PROC1;
/
EXEC PROC1();


CREATE OR REPLACE PROCEDURE PROC2 IS
    MYEXCEPTION EXCEPTION;
    n NUMBER := 10;
BEGIN 
    FOR i IN 10 .. 20 LOOP
    DBMS_OUTPUT.PUT_LINE(i*i);
    IF i * 2 = 10 THEN
        RAISE MYEXCEPTION;
    END IF;
END LOOP;

EXCEPTION 
    WHEN MYEXCEPTION THEN
    RAISE_APPLICATION_ERROR(-20015, 'VOCE CAIU NA EXCEPTION');
END;


